name: 09 - Using Functions

on:
  pull_request:
  workflow_dispatch:
  
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo "${{ github.event.pull_request.title }}"

      - name: Print PR labels
        run: echo "${{ toJson(github.event.pull_request.labels) }}"

      - name: Bug step
        if: !cancelled() && contains(github.event.pull_request.title, 'fix')
        run: echo "I am a bug fix"

      - name: Sleep for 20 seconds
        shell: bash
        run: sleep 20s

      - name: Failing Step
        run: exit 1

      - name: I will be skipped
        if: success()
        run: echo "I will print if previous steps succeed"

      - name: I will execute
        if: failure()
        run: echo "I will print if any previous step fails"

      - name: I will execute when cancelled
        if: cancelled()
        run: echo "Workflow has been cancelled"
