name: 11 - Working with Inputs

on:
  workflow_dispatch: 
    inputs:
      dry-run:
        type: boolean
        default: false
        description: Skip deployment and only print build output
      target:
        type: environment
        description: Which environment the workflow will target
      tags:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: Release from which to build and deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building from tag ${{ inputs.tags }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: ${{ inputs.target }}
    if: success() && inputs.dry-run == false
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ inputs.target }}"
